import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  DomainStoryGrammarGeneratedModule as DomainStoryGeneratedModule,
  MermaidGeneratedSharedModule,
} from '../generated/module.js';
import { DomainStoryTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `DomainStory` services.
 */
interface DomainStoryAddedServices {
  parser: {
    TokenBuilder: DomainStoryTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `DomainStory` services.
 */
export type DomainStoryServices = LangiumCoreServices & DomainStoryAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `DomainStory` services.
 */
export const DomainStoryModule: Module<
  DomainStoryServices,
  PartialLangiumCoreServices & DomainStoryAddedServices
> = {
  parser: {
    TokenBuilder: () => new DomainStoryTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createDomainStoryServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  DomainStory: DomainStoryServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const DomainStory: DomainStoryServices = inject(
    createDefaultCoreModule({ shared }),
    DomainStoryGeneratedModule,
    DomainStoryModule
  );
  shared.ServiceRegistry.register(DomainStory);
  return { shared, DomainStory };
}
